In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/my notes/NLP/smsspamcollection.tsv', sep='\t')

In [ ]:
data.head()

In [ ]:
data.shape

(5572, 4)

In [ ]:
len(data['message'][0])

In [ ]:
len(data)

In [ ]:
data.isnull().sum()

In [ ]:
data['label'].value_counts()

In [ ]:
# data['label']

In [ ]:
data['punct'].describe()

In [ ]:
x = data[['length','punct']]
y = data['label']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=42)

In [ ]:
print('train size-->',x_train.shape)
print('test size-->',x_test.shape)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
multi_nb = MultinomialNB()
multi_nb.fit(x_train,y_train)

In [ ]:
y_pred = multi_nb.predict(x_test)
y_pred

In [ ]:
from sklearn import metrics

In [ ]:
print(metrics.confusion_matrix(y_test,y_pred))

In [ ]:
print('Accuracy of tested and predicted--->',metrics.accuracy_score(y_test,y_pred))

In [ ]:
print('Training Accuracy--->',multi_nb.score(x_train,y_train))

In [ ]:
print('Testing Accuracy--->',multi_nb.score(x_test,y_test))

In [ ]:
# Adding labels to the confusion_metrix

In [ ]:
data2 = pd.DataFrame(metrics.confusion_matrix(y_test,y_pred),index=['ham','spam'],columns=['ham','spam'])
data2

In [ ]:
# Boosting the accuracy using feature extraction of NLP on the same dataset using TfidfVectorizer.

In [ ]:
data.head()

In [ ]:
x1 = data['message']
y1 = data['label']

In [ ]:
x1.shape

(5572,)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train1,x_test1,y_train1,y_test1 = train_test_split(x1,y1,test_size=0.30,random_state=42)

In [ ]:
x_train1.shape

(3900,)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
#############################################################################################

In [ ]:
from sklearn.pipeline import Pipeline

In [ ]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),
                     ('multi_nb',MultinomialNB())])

In [ ]:
text_clf.fit(x_train1,y_train1)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('multi_nb', MultinomialNB())])

In [ ]:
y_pred_tfidf_mnb = text_clf.predict(x_test1)
y_pred_tfidf_mnb

array(['ham', 'ham', 'ham', ..., 'ham', 'spam', 'ham'], dtype='<U4')

In [ ]:
print(metrics.confusion_matrix(y_test1,y_pred_tfidf_mnb))

[[1448    0]
 [  62  162]]


In [ ]:
print('Accuracy of tested and predicted--->',metrics.accuracy_score(y_test1,y_pred_tfidf_mnb))

Accuracy of tested and predicted---> 0.9629186602870813


In [ ]:
data3 = pd.DataFrame(metrics.confusion_matrix(y_test1,y_pred_tfidf_mnb),index=['ham','spam'],columns=['ham','spam'])
data3

ham  spam
ham   1448     0
spam    62   162

In [ ]:
#################################################################################################################

In [ ]:
from sklearn.svm import SVC

In [ ]:
text_clf1 = Pipeline([('tfidf',TfidfVectorizer()),
                     ('svc',SVC())])

In [ ]:
text_clf1.fit(x_train1,y_train1)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('svc', SVC())])

In [ ]:
y_pred_tfidf_svc = text_clf1.predict(x_test1)
y_pred_tfidf_svc

array(['ham', 'ham', 'ham', ..., 'ham', 'spam', 'ham'], dtype=object)

In [ ]:
print(metrics.confusion_matrix(y_test1,y_pred_tfidf_svc))

[[1448    0]
 [  23  201]]


In [ ]:
print(metrics.accuracy_score(y_test1,y_pred_tfidf_svc))

0.986244019138756


In [ ]:
print(text_clf1.score(x_train1,y_train1))

0.9982051282051282


In [ ]:
print(text_clf1.score(x_test1,y_test1))

0.986244019138756


In [ ]:
data4 = pd.DataFrame(metrics.confusion_matrix(y_test1,y_pred_tfidf_svc),index=['ham','spam'],columns=['ham','spam'])
data4

ham  spam
ham   1448     0
spam    23   201

In [ ]:
#################################################################################################

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
text_clf2 = Pipeline([('tfidf',TfidfVectorizer()),
                     ('knc',KNeighborsClassifier())])

In [ ]:
text_clf2.fit(x_train1,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('knc', KNeighborsClassifier())])

In [ ]:
y_pred_tfidf_knc = text_clf2.predict(x_test1)
y_pred_tfidf_knc

array(['ham', 'ham', 'ham', ..., 'ham', 'ham', 'ham'], dtype=object)

In [ ]:
print(metrics.confusion_matrix(y_test1,y_pred_tfidf_knc))

[[1448    0]
 [ 154   70]]


In [ ]:
print(metrics.accuracy_score(y_test1,y_pred_tfidf_knc))

In [ ]:
data5 = pd.DataFrame(metrics.confusion_matrix(y_test1,y_pred_tfidf_knc),index=['ham','spam'],columns=['ham','spam'])
data5

In [ ]:
dataset_acuuracies = pd.DataFrame({'Multinomialnb':pd.Series(metrics.accuracy_score(y_test1,y_pred_tfidf_mnb)),
                                    'SVC':pd.Series(metrics.accuracy_score(y_test1,y_pred_tfidf_svc)),
                                   'KNeighbours':pd.Series(metrics.accuracy_score(y_test1,y_pred_tfidf_knc))})

In [ ]:
dataset_acuuracies

Multinomialnb       SVC  KNeighbours
0       0.962919  0.986244     0.907895